services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  asynq_ui:
    image: hibiken/asynqmon
    ports:
      - "8080:8080"
    environment:
      REDIS_URL: "redis://redis:6379"
      READ_ONLY: false
