name: CI

on:
  push:

jobs:
  test-redis:
    name: Test v${{ matrix.version }} with Redis
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    strategy:
      matrix:
        version: [18, 20, 22]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install packages
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: Run tests
        env:
          DB_URL: redis://localhost:6379
        run: |
          cd ./packages/asynq
          pnpm test

  test-valkey:
    name: Test v${{ matrix.version }} with Valkey
    runs-on: ubuntu-latest
    services:
      valkey:
        image: valkey/valkey
        ports:
          - 6379:6379

    strategy:
      matrix:
        version: [18, 20, 22]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install packages
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: Run tests
        env:
          DB_URL: redis://localhost:6379
        run: |
          cd ./packages/asynq
          pnpm test

  publish-npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.6.0

      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.PKG_NPM_TOKEN}}

      - run: |
          # Build package 
          pnpm --filter asynq-node build;
          
          pnpm --filter asynq-node publish --no-git-checks --access=public
